version: "3"
services:
  app:
    container_name: vidjot
    restart: always
    build: ./
    ports:
      - "5000:5000"
    volumes:
      - .:/app  
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data/db
    ports:
      - "27017:27017"